import type { StoreCategory, ShippingOption, StoreProduct } from '@/types/store';

export const STORE_NAME = 'KineBytes Shop';
export const STORE_TAGLINE = 'Hardware atlético inteligente para alto rendimiento';

export const CATEGORIES: StoreCategory[] = [
  { slug: 'interactive-hardware', name: 'Hardware Interactivo', description: 'Conos, módulos y dispositivos listos para entrenamiento en campo.', icon: '⚡', accent: 'from-emerald-500/20 to-emerald-500/5' },
  { slug: 'sensors', name: 'Sensores', description: 'Componentes para medir velocidad, reacción, carga y precisión.', icon: '📡', accent: 'from-cyan-500/20 to-cyan-500/5' },
  { slug: 'training-packs', name: 'Training Packs', description: 'Bundles para acelerar la implementación en equipos y academias.', icon: '🎯', accent: 'from-violet-500/20 to-violet-500/5' },
  { slug: 'software', name: 'Software', description: 'Licencias y módulos digitales para dashboards y analítica.', icon: '💻', accent: 'from-amber-500/20 to-amber-500/5' },
  { slug: 'accessories', name: 'Accesorios', description: 'Baterías, soportes, kits de montaje y mantenimiento.', icon: '🔧', accent: 'from-sky-500/20 to-sky-500/5' },
];

export const SHIPPING_OPTIONS: ShippingOption[] = [
  { id: 'standard', label: 'Standard', description: 'Entrega regular para productos en stock.', price: 12, eta: '3-5 días hábiles' },
  { id: 'express', label: 'Express', description: 'Prioridad de despacho para entrenamientos próximos.', price: 24, eta: '24-48 horas' },
  { id: 'pickup', label: 'Local Pickup', description: 'Retiro en punto de entrega autorizado.', price: 0, eta: 'Mismo día' },
];

export const MOCK_PRODUCTS: StoreProduct[] = [
  { id: 'prod-kb-cone-pro', slug: 'cono-interactivo-pro', name: 'Cono Interactivo Pro', shortDescription: 'Cono luminoso con telemetría y respuesta inmediata.', description: 'Diseñado para pruebas de agilidad, velocidad y reacción con control desde panel web y sincronización con múltiples dispositivos. Incluye firmware actualizable OTA y compatibilidad con el ecosistema completo KineBytes.', category: 'interactive-hardware', price: 149, compareAtPrice: 179, rating: 4.9, reviewCount: 42, stock: 'in-stock', condition: 'new', features: ['Control por ESP32', 'LED RGB de alta visibilidad', 'Modo reacción y timing', 'Sincronización multiunidad', 'Firmware OTA', 'IP65 resistente al agua'], specifications: [{ label: 'Autonomía', value: '10 h' }, { label: 'Conectividad', value: 'WiFi + BLE' }, { label: 'Peso', value: '420 g' }, { label: 'Dimensiones', value: '15 × 15 × 22 cm' }, { label: 'Batería', value: 'Li-Po 3000mAh' }], variants: [{ id: 'black', label: 'Graphite', priceDelta: 0, stock: 14 }, { id: 'cyan', label: 'Kine Cyan', priceDelta: 10, stock: 8 }, { id: 'lime', label: 'Field Lime', priceDelta: 10, stock: 5 }], tags: ['featured', 'athletics', 'hardware'], images: [], accent: 'from-emerald-500/25 via-emerald-500/10 to-transparent', isFeatured: true },
  { id: 'prod-kb-sensor-beam', slug: 'sensor-beam-agility', name: 'Sensor Beam Agility', shortDescription: 'Sensor para medir paso, reacción y precisión.', description: 'Un módulo de detección pensado para automatizar pruebas de agilidad con métricas exportables al dashboard. Latencia ultra-baja de 2ms para mediciones profesionales.', category: 'sensors', price: 99, compareAtPrice: 119, rating: 4.7, reviewCount: 31, stock: 'low-stock', condition: 'new', features: ['Latencia 2ms', 'Lecturas precisas', 'Montaje rápido', 'Doble sensor infrarrojo'], specifications: [{ label: 'Rango', value: '15 m' }, { label: 'Batería', value: '48 h' }, { label: 'Compatibilidad', value: 'KineBytes suite' }, { label: 'Peso', value: '280 g' }], variants: [{ id: 'default', label: 'Standard', priceDelta: 0, stock: 5 }], tags: ['sensor', 'tracking', 'field'], images: [], accent: 'from-cyan-500/25 via-cyan-500/10 to-transparent' },
  { id: 'prod-kb-pro-pack', slug: 'training-pack-pro', name: 'Training Pack Pro', shortDescription: 'Bundle completo para sesiones de alto rendimiento.', description: 'Incluye hardware, soporte de software y presets de entrenamiento para implementar una estación KineBytes completa. Ideal para academias y equipos profesionales.', category: 'training-packs', price: 499, compareAtPrice: 599, rating: 5.0, reviewCount: 18, stock: 'in-stock', condition: 'bundle', features: ['3 Conos Interactivos Pro', '1 Sensor Beam Agility', '1 Licencia Software Pro (3 meses)', 'Kit de montaje incluido', 'Soporte prioritario'], specifications: [{ label: 'Instalación', value: '1 día' }, { label: 'Soporte', value: 'Incluido 6 meses' }, { label: 'Ahorro', value: '20%' }], variants: [{ id: 'bundle-3', label: 'Pack 3 Conos', priceDelta: 0, stock: 9 }, { id: 'bundle-6', label: 'Pack 6 Conos', priceDelta: 320, stock: 4 }], tags: ['bundle', 'academy', 'featured'], images: [], accent: 'from-violet-500/25 via-violet-500/10 to-transparent', isFeatured: true },
  { id: 'prod-kb-license-pro', slug: 'software-license-pro', name: 'Licencia Software Pro', shortDescription: 'Acceso al dashboard y módulos avanzados.', description: 'Activa analítica avanzada, reportes, administración de dispositivos y roles de subadmin en una sola licencia. Integración directa con el dashboard KineByte.', category: 'software', price: 49, rating: 4.8, reviewCount: 72, stock: 'in-stock', condition: 'new', features: ['Dashboard completo', 'Roles avanzados', 'Exportación CSV/PDF', 'API access'], specifications: [{ label: 'Duración', value: 'Mensual' }, { label: 'Usuarios', value: 'Ilimitados' }, { label: 'Integración', value: 'Supabase ready' }], variants: [{ id: 'monthly', label: 'Mensual', priceDelta: 0, stock: 999 }, { id: 'yearly', label: 'Anual (ahorra 20%)', priceDelta: 420 - 49, stock: 999 }], tags: ['software', 'subscription', 'featured'], images: [], accent: 'from-amber-500/25 via-amber-500/10 to-transparent', isFeatured: true },
  { id: 'prod-kb-accessories-kit', slug: 'accessories-maintenance-kit', name: 'Kit de Mantenimiento', shortDescription: 'Accesorios para calibración, soporte y reemplazo.', description: 'Incluye soportes, cables y piezas de repuesto para asegurar continuidad operacional en campo. Compatible con todo el ecosistema KineBytes.', category: 'accessories', price: 39, rating: 4.6, reviewCount: 24, stock: 'in-stock', condition: 'bundle', features: ['Cables reforzados', 'Herramientas base', 'Soportes modulares', 'Estuche de transporte'], specifications: [{ label: 'Contenido', value: '8 piezas' }, { label: 'Uso', value: 'Field support' }, { label: 'Compatibilidad', value: 'Todo el ecosistema' }], variants: [{ id: 'kit', label: 'Maintenance Kit', priceDelta: 0, stock: 27 }], tags: ['accessory', 'maintenance'], images: [], accent: 'from-sky-500/25 via-sky-500/10 to-transparent' },
  { id: 'prod-kb-reaction-pad', slug: 'reaction-pad-elite', name: 'Reaction Pad Elite', shortDescription: 'Panel de reacción táctil con métricas en tiempo real.', description: 'Panel de pared con sensores capacitivos para medir tiempo de reacción táctil. Se integra con el dashboard para comparar sesiones y generar informes de progreso.', category: 'interactive-hardware', price: 229, compareAtPrice: 269, rating: 4.8, reviewCount: 15, stock: 'in-stock', condition: 'new', features: ['8 zonas táctiles', 'Display LED integrado', 'Modos de juego preconfigurados', 'Bluetooth 5.0'], specifications: [{ label: 'Zonas', value: '8 capacitivas' }, { label: 'Batería', value: '12 h' }, { label: 'Montaje', value: 'Pared/Trípode' }, { label: 'Peso', value: '850 g' }], variants: [{ id: 'standard', label: 'Standard', priceDelta: 0, stock: 10 }, { id: 'pro', label: 'Pro (12 zonas)', priceDelta: 70, stock: 6 }], tags: ['hardware', 'reaction', 'training'], images: [], accent: 'from-emerald-500/25 via-emerald-500/10 to-transparent' },
  { id: 'prod-kb-speed-gate', slug: 'speed-gate-duo', name: 'Speed Gate Duo', shortDescription: 'Puertas de velocidad con cronómetro automático.', description: 'Par de sensores inalámbricos para medir sprints, parciales y aceleraciones. Conectividad WiFi para transmisión directa al dashboard.', category: 'sensors', price: 189, rating: 4.5, reviewCount: 8, stock: 'in-stock', condition: 'new', features: ['Par de sensores', 'Cronómetro 0.001s', 'WiFi directo', 'Batería 72h'], specifications: [{ label: 'Precisión', value: '±1ms' }, { label: 'Rango', value: '30 m' }, { label: 'Batería', value: '72 h' }], variants: [{ id: 'duo', label: 'Par (2 gates)', priceDelta: 0, stock: 12 }, { id: 'quad', label: 'Pack 4 gates', priceDelta: 180, stock: 5 }], tags: ['sensor', 'speed', 'sprint'], images: [], accent: 'from-cyan-500/25 via-cyan-500/10 to-transparent' },
  { id: 'prod-kb-team-license', slug: 'team-license-enterprise', name: 'Licencia Team Enterprise', shortDescription: 'Licencia para equipos con roles y analytics avanzados.', description: 'Pensada para clubes y academias. Incluye multi-coach, roles de administrador, reportes comparativos entre atletas y exportación programática vía API.', category: 'software', price: 149, compareAtPrice: 199, rating: 4.9, reviewCount: 11, stock: 'in-stock', condition: 'new', features: ['Multi-coach', 'Comparación de atletas', 'Exportación API', 'Soporte prioritario'], specifications: [{ label: 'Coaches', value: 'Hasta 10' }, { label: 'Atletas', value: 'Ilimitados' }, { label: 'Almacenamiento', value: '100 GB' }], variants: [{ id: 'monthly', label: 'Mensual', priceDelta: 0, stock: 999 }, { id: 'yearly', label: 'Anual (ahorra 25%)', priceDelta: 1192 - 149, stock: 999 }], tags: ['software', 'enterprise', 'teams'], images: [], accent: 'from-amber-500/25 via-amber-500/10 to-transparent' },
];
